CREATE DATABASE IF NOT EXISTS innovation_ecosystem_2026
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE innovation_ecosystem_2026;

CREATE TABLE IF NOT EXISTS institution_registrations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    institution_name VARCHAR(255) NOT NULL,
    institution_type VARCHAR(100) NOT NULL,
    institution_address TEXT NOT NULL,
    ward_area VARCHAR(255) NOT NULL,
    total_student_strength INT NOT NULL,
    coordinator_name VARCHAR(255) NOT NULL,
    designation_department VARCHAR(255) NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    awareness_methods TEXT NOT NULL,
    students_reached INT NOT NULL,
    challenge_themes TEXT NOT NULL,
    entry_types TEXT NOT NULL,
    total_entries INT NOT NULL,
    shortlisted_entries INT NOT NULL,
    shortlisted_details TEXT NOT NULL,
    activity_report TEXT NOT NULL,
    activity_photos_link TEXT NULL,
    activity_video_link TEXT NULL,
    maps_link TEXT NULL,
    government_supported VARCHAR(10) NOT NULL,
    government_count INT NULL,
    government_project_details TEXT NULL,
    government_reel_folder TEXT NULL,
    patent_count INT NOT NULL DEFAULT 0,
    design_count INT NOT NULL DEFAULT 0,
    copyright_count INT NOT NULL DEFAULT 0,
    trademark_count INT NOT NULL DEFAULT 0,
    startup_data TEXT NULL,
    innovation_research_data TEXT NULL,
    ecosystem_support TEXT NOT NULL,
    specific_facility TEXT NULL,
    confirmation TINYINT(1) NOT NULL DEFAULT 0,
    authorized_coordinator VARCHAR(255) NOT NULL,
    confirmation_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ecosystem_registrations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    registering_as TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    vidhan_sabha VARCHAR(150) NOT NULL,
    ward_number VARCHAR(50) NOT NULL,
    area_locality VARCHAR(255) NOT NULL,
    google_maps_location TEXT NULL,
    organisation_name VARCHAR(255) NULL,
    designation_role VARCHAR(255) NOT NULL,
    website_social_link TEXT NULL,
    expertise TEXT NOT NULL,
    support_you_can_provide TEXT NOT NULL,
    support_description TEXT NULL,
    innovation_startup_name VARCHAR(255) NULL,
    problem_being_addressed TEXT NULL,
    innovation_solution TEXT NULL,
    current_stage VARCHAR(100) NULL,
    ipr_status TEXT NULL,
    project_demo_link TEXT NULL,
    investment_type TEXT NULL,
    startup_stage_interest TEXT NULL,
    preferred_sector TEXT NULL,
    investment_funding_range VARCHAR(255) NULL,
    mentor_expertise TEXT NULL,
    mentor_support_offered TEXT NULL,
    mentor_availability VARCHAR(100) NULL,
    institution_type VARCHAR(150) NULL,
    facilities_capabilities TEXT NULL,
    number_of_startups_projects_iprs TEXT NULL,
    institution_ecosystem_support TEXT NULL,
    support_type TEXT NULL,
    support_details TEXT NULL,
    individual_contribution TEXT NULL,
    individual_contribution_details TEXT NULL,
    consent TINYINT(1) NOT NULL DEFAULT 0,
    additional_information TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
